-- Enable PostGIS for location
create extension if not exists postgis;

-- 1. POSTS TABLE
create table public.posts (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  author_user_id uuid references auth.users(id), -- Private, not exposed to client via select
  category text not null, -- 'positive', 'rant', 'general', 'found'
  subtype text, -- 'gratitude', 'traffic', etc.
  status text default 'published', -- 'published', 'pending', 'rejected', 'removed'
  text_content text, -- Null for Found items
  
  -- Location (Fuzzed)
  location_geog geography(Point),
  location_label text, -- "Approx near Central Park"
  location_precision_m int, -- e.g. 500
  
  -- Found Fields
  found_item_type text,
  found_item_class text,
  found_datetime timestamptz,
  found_disposition text,
  found_business_type text,
  
  -- Internal
  moderation_reason text,
  client_hash text
);

create index posts_geo_index on public.posts using GIST (location_geog);
create index posts_category_index on public.posts (category);

-- 2. REPLIES TABLE
create table public.replies (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  post_id bigint references public.posts(id),
  author_user_id uuid references auth.users(id),
  status text default 'published',
  text_content text not null,
  moderation_reason text
);

-- 3. THREAD ALIASES (Anonymity)
create table public.thread_aliases (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id),
  user_id uuid references auth.users(id),
  alias_name text not null,
  is_op boolean default false,
  unique(post_id, user_id)
);

-- 4. REPORTS
create table public.reports (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  reporter_user_id uuid references auth.users(id),
  target_type text not null, -- 'post', 'reply'
  target_id bigint not null,
  reason text not null,
  note text,
  status text default 'open' -- 'open', 'resolved', 'dismissed'
);

-- 5. USER PENALTIES
create table public.user_penalties (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  user_id uuid references auth.users(id),
  penalty_type text not null, -- 'warn', 'timeout', 'ban'
  starts_at timestamptz default now(),
  ends_at timestamptz,
  reason text
);

-- RLS POLICIES

-- Posts: Public Read (Only published)
alter table public.posts enable row level security;
create policy "Public can view published posts"
  on public.posts for select
  using (status = 'published');

-- Client cannot INSERT/UPDATE/DELETE posts directly (Must use Netlify Functions)
-- No insert/update/delete policies for anon/authenticated roles.

-- Replies: Public Read (Only published)
alter table public.replies enable row level security;
create policy "Public can view published replies"
  on public.replies for select
  using (status = 'published');

-- Thread Aliases: No Public Read (Managed by Server Functions, added to response)
alter table public.thread_aliases enable row level security;
-- No select policy for public.

-- Reports: No Public Read. Insert via Function only (or highly restricted if direct)
alter table public.reports enable row level security;

-- Admin Role & Policies (Optional: if we use Supabase Auth for Admin dashboard)
-- For now, relying on Netlify Functions with Service Role for admin actions.

-- 6. USER PROFILES
create table public.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  display_name text,
  bio text,
  avatar_seed text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- RLS for Profiles
alter table public.profiles enable row level security;

-- STRICT: Users can ONLY view/edit their OWN profile.
create policy "Users can view their own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Users can insert their own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

create policy "Users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- 7. UPDATE POSTS TABLE
-- Add avatar_seed to posts to snapshot the avatar at the time of posting
alter table public.posts add column avatar_seed text;
-- Add author_alias to snapshot the display name at the time of posting
alter table public.posts add column author_alias text;


